### ISSUE TITLE
elektronn-profile

### ISSUE THREAD

**Issue by emoebel** [ELEKTRONN/ELEKTRONN#5]
Hello,

This morning I wanted to make predictions with a new CNN architecture that was learning all night. But before I wanted to check which was the optimal input size using the script elektronn-profile. By launching it from the same folder I launched the training, I got a bad surprise : elektronn-profile has overwritten the Debug folder, so I lost all the parameters of my freshly trained CNN :-(

I'll now be more carefull, but it would be nice if elektronn-profile would not overwrite any data ;-)

Cheers,
Lazyleaf

**Comment by xeray** [comment]
Oh my bad. I hope you can recover your training soon.
